### ISSUE TITLE
Use Issues manage TODO papers

### ISSUE THREAD

**Issue by changkun** [LMU-AIJC/lmu-aijc.github.io#1]
It is hard to choose a paper for our next reading, this issue proposes to use the feature "Issues" for managing all TODO papers.

More specific, all members can always open an issue with the paper title, link, reason as well as an available discussion date. Then organizers can directly decide and choose which could be the next meeting.

For instance, assume that I opened an issue with the title `Matrix Capsule with EM Routing` with label "Paper", the content of this issue is as follows:

---
- Link: https://openreview.net/pdf?id=HJWLfGWRb
- Reason: ICLR 2018 Accepted paper, follow up research for "capsule network"
- A possible discussion date starts from March 5th, 2018
---

If staff accept this paper for future reading, just comment `Accept`, labeling it as `todo` and pick up a date for the future group reading, otherwise comment reasons then close the issue.

**Comment by EmCity** [comment]
I like the idea and we should talk this over at our next meeting!

**Comment by georgiaolympia** [comment]
I think this is a great idea as well ! Thanks for suggesting it, @changkun !

**Comment by changkun** [comment]
Great to hear both of you accept this idea, then I am going to close this issue :)
